### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by nightfury1204** [kubevault/project#28]
concepts
 - Vault Server Crds
   - VaultServer
   - Storage Options
     - etcd
     - s3
     - gcs
   - Unsealer
     - 
     - 
   - Auth
     - Service Account
     - AWS IAM

 - Policy CRDs
   - Policy
   - PolicyBinding

---------------------------------------------

setup
README.md
 - Operator
   - Install
   - Uninstall
   - Upgrade
 - CSI Driver
   - Install
   - Uninstall
   - Upgrade
 - Kubectl Plugin
   - Install
   - Uninstall
   - Upgrade

---------------------------------------------

guides
- Deploy Vault in Kubernetes (vault operator)
  - provider specific vault deploy
   - eks
   - aks
   - gke
   - kops(?)

- external vault with operator and csi driver demo
  - AppBinding
  - Auth with external (AWS IAM etc)

- Policy Management
  - Policy / PolicyBinding tutorial
  - example: https://kubernetes.io/docs/reference/access-authn-authz/rbac/

- Secret Engines
  - KV
    - csi-driver
  - AWS
    - AWSAccessKeyRequest (crd details)
    - csi-driver ()

  - Postgres
    - PostgresRole, RoleBinding, AppBinding (crd details)
    - DBAccessRequest
    - csi-driver

  - MongoDB
    - MongoDBRole, RoleBinding, AppBinding (crd details)
    - DBAccessRequest
    - csi-driver

  - MySQL
    - MySQLRole, RoleBinding, AppBinding (crd details)
    - DBAccessRequest
    - csi-driver

Monitoring
 - Overview (Vault Server Metrics) + go to operator_monitoring.md for monitoring operator0
 - Built-in (vautl server metrics)
 - CoreOS operator (vautl server metrics)
 - Grafana (vautl server dashboard)
 - Operator + CSI Driver Metric (kube-state-metrics)

---
Chart

Operator + CSI Driver {{- if .Values.monitoring.operator }}
https://github.com/appscode/stash/pull/606/files

------------
examples
images

**Comment by tamalsaha** [comment]
```
https://raw.githubusercontent.com/kubevault/docs/master/docs/ > https://raw.githubusercontent.com/kubevault/docs/*******/docs/
```
