### ISSUE TITLE
KubeVault website Hugo issue

### ISSUE THREAD

**Issue by tamalsaha** [kubevault/project#41]
`[09:54:49] ERROR 2019/02/22 09:54:49 Error while rendering "page" in "docs/0.1.0/setup/cli/": template: docs/single.html:21:3: executing "docs/single.html" at <partial "docs-sectio...>: error calling partial: template: partials/docs-section-menu.html:19:49: executing "partials/docs-section-menu.html" at <.Params.menu_name>: range can't iterate over <nil>`

`[09:54:49] WARN 2019/02/22 09:54:49 template: docs/single.html:21:3: executing "docs/single.html" at <partial "docs-sectio...>: error calling partial: template: partials/docs-section-menu.html:19:49: executing "partials/docs-section-menu.html" at <.Params.menu_name>: range can't iterate over <nil>`

`[09:54:49] WARN 2019/02/22 09:54:49 [en] Unable to locate layout for "taxonomyTerm": [tags/tag.terms.en.html.html tags/terms.en.html.html tags/list.en.html.html tags/tag.terms.html.html tags/terms.html.html tags/list.html.html tags/tag.terms.en.html tags/terms.en.html tags/list.en.html tags/tag.terms.html tags/terms.html tags/list.html taxonomy/tag.terms.en.html.html taxonomy/terms.en.html.html taxonomy/list.en.html.html taxonomy/tag.terms.html.html taxonomy/terms.html.html taxonomy/list.html.html taxonomy/tag.terms.en.html taxonomy/terms.en.html taxonomy/list.en.html taxonomy/tag.terms.html taxonomy/terms.html taxonomy/list.html tag/tag.terms.en.html.html tag/terms.en.html.html tag/list.en.html.html tag/tag.terms.html.html tag/terms.html.html tag/list.html.html tag/tag.terms.en.html tag/terms.en.html tag/list.en.html tag/tag.terms.html tag/terms.html tag/list.html _default/tag.terms.en.html.html _default/terms.en.html.html _default/list.en.html.html _default/tag.terms.html.html _default/terms.html.html _default/list.html.html _default/tag.terms.en.html _default/terms.en.html _default/list.en.html _default/tag.terms.html _default/terms.html _default/list.html]`

**Comment by sajibcse68** [comment]
https://github.com/kubevault/docs/blob/master/docs/setup/cli/install.md

Change `product_KubeVault_0.1.0` -> `docs_0.1.0`

**Comment by tamalsaha** [comment]
Fixed
